apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuplus-prod
spec:
  destination:
    name: ''
    namespace: tuplus-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: scripts/deploy/production
    repoURL: 'https://github.com/codelab-kr/microservices-starter-manifest.git'
    targetRevision: HEAD
  sources: []
  project: default
