apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuplus-seoul
spec:
  destination:
    namespace: tuplus
    server: 'https://kubernetes.default.svc'
  source:
    path: scripts/deploy/development
    repoURL: 'https://github.com/codelab-kr/microservices-starter.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
