apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    stream {
        server {
            listen 6379;
            proxy_pass redis:6379;
        }
        server {
            listen 3306;
            proxy_pass mysql:3306;}
        server {
            listen 27017;
            proxy_pass mongodb:27017;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.25.3
    ports:
    - containerPort: 6379
    - containerPort: 3306
    - containerPort: 27017
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: nginx