apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret-seoul
      containers:
        - name: users
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-users:0.1
          envFrom:
            - configMapRef:
                name: mysql-env
          env:
            - name: 'SERVICE_NAME'
              value: 'users'
          command: ['/bin/sh', '-c']
          args: ['yarn start:developmnet users']
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능
  ports:
    - protocol: TCP
      port: 80
