apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videos
  template:
    metadata:
      labels:
        app: videos
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret-seoul
      containers:
        - name: videos
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-videos:0.1
          envFrom:
            - configMapRef:
                name: mongo-env
          env:
            - name: 'SERVICE_NAME'
              value: 'videos'
          command: ['/bin/sh', '-c']
          args: ['yarn start:developmnet videos']
---
apiVersion: v1
kind: Service
metadata:
  name: videos
spec:
  selector:
    app: videos
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능
  ports:
    - protocol: TCP
      port: 80
