apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
data:
  PORT: '4000'
  EXPIRESIN: '3600000'
  REDIS_URL: 'redis://redis:6379'
  SESSION_AUTH: 'true'
  BASE_URL: 'https://development.code-lab.kr'
  STORAGE_URL: 'https://storage.code-lab.kr'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret-seoul
      containers:
        - name: api
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/production-api:0.1
          envFrom:
            - configMapRef:
                name: api-env
          env:
            - name: 'SERVICE_NAME'
              value: 'api'
            - name: 'SECRET'
              valueFrom:
                secretKeyRef:
                  name: tuplus-secret
                  key: SECRET
            - name: 'GOOLGE_CLIENT_ID'
              valueFrom:
                secretKeyRef:
                  name: tuplus-secret
                  key: GOOLGE_CLIENT_ID
            - name: 'GOOGLE_CLIENT_SECRET'
              valueFrom:
                secretKeyRef:
                  name: tuplus-secret
                  key: GOOGLE_CLIENT_SECRET
          command: ['/bin/sh', '-c']
          args: ['yarn start:production api']
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
